### ISSUE TITLE
Handle when an Industry is Missing Step 2 in the Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1440] opened 2022-01-26 22:23 UTC
TBD

## Acceptance criteria

- Implement design

## Notes

- [ ] PO Approval
- [ ] UX Review
- [ ] Content Review

**Comment by skeeJay** [comment] 2022-02-02 20:00
@aaronvux This may be a dupe of #1469

**Closed** 2022-02-04 15:15 UTC
Labels: (:star: ), epic: Navigator Improvements
