### ISSUE TITLE
Design System: Color Updates

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1431] opened 2022-01-26 15:57 UTC
### Dev Change Required

As a user, i need to differentiate between links i've visited vs not etc etc

- [ ] Link Color: link (primary), hover (primary-vivid), active (primary-dark ie pressed), visited ("primary darker" tbd). Add "primary-darker" to library.
- [ ] Add new lightest grey F6F6F6 -- check accessibility first
- [ ] Let Faraz know before updating / Dev change required

**Comment by FarazA22** [comment] 2022-01-31 15:56
@carye3 Hold off on this ticket, I think the issue is on my end and not yours.

**Comment by carye3** [comment] 2022-01-31 20:15
@FarazA22 which issue is on your end -- the link color or the background grey color?

**Comment by FarazA22** [comment] 2022-02-01 19:02
@carye3 the link color was using the old primary color which caused the contrast issue. I've updated it to the Primary token and it's no longer an issue. You can close this ticket.

**Comment by carye3** [comment] 2022-02-02 14:46
Excellent ty @FarazA22

**Closed** 2022-02-02 14:47 UTC
